(()=>{'use strict';const $=s=>document.querySelector(s),dec=new TextDecoder(),view=(b)=>new DataView(b),u32=(v,o)=>v.getUint32(o,true),u64=(v,o)=>Number(v.getBigUint64(o,true)),str=(b,v,o)=>{const p=u32(v,o),n=u32(v,o+4);return p+n<=b.byteLength?dec.decode(new Uint8Array(b,p,n)):''};const state={path:new URLSearchParams(location.search).get('path')||'~',homePath:null,parent:null,entries:[],selected:null,openers:[],previewController:null,previewURL:null,typeaheadPrefix:'',typeaheadLastUpdated:0,lastTouchTap:null,suppressedTouchClick:null};
function filesFetch(input, options = {}) {
    const url = new URL(input, location.href);
    const headers = new Headers(options.headers);
    if (url.origin === location.origin && url.pathname.startsWith('/api/')) {
        const context = window.outerLoop?.sessionContext;
        if (context?.username) headers.set('X-Files-User', context.username);
    }
    return fetch(input, { ...options, headers });
}

function parseFiles(b){const v=view(b);if(u32(v,0)!==0x534c4646)throw Error('Invalid file list');const count=u32(v,8),rowSize=u32(v,12),off=u32(v,16);return{path:str(b,v,32),parent:str(b,v,40),entries:Array.from({length:count},(_,i)=>{const o=off+i*rowSize;return{name:str(b,v,o),path:str(b,v,o+8),mode:str(b,v,o+16),directory:!!u32(v,o+24),access:u32(v,o+28),size:u64(v,o+32),modified:u64(v,o+40)}})}}
function parseOpeners(b){const v=view(b);if(u32(v,0)!==0x504f464f)return[];const n=u32(v,8),sz=u32(v,12),off=u32(v,16);return Array.from({length:n},(_,i)=>{let o=off+i*sz;return{contentType:str(b,v,o),serviceID:str(b,v,o+8),name:str(b,v,o+16),socket:str(b,v,o+24),url:str(b,v,o+32),owner:str(b,v,o+40)}})}
const fmtSize=n=>n<1024?`${n} bytes`:n<1048576?`${Math.ceil(n/1024)} KB`:n<1073741824?`${(n/1048576).toFixed(1)} MB`:`${(n/1073741824).toFixed(1)} GB`;const fmtDate=n=>n?new Date(n).toLocaleString([], {dateStyle:'medium',timeStyle:'short'}):'—';
async function load(path=state.path){$('#status').textContent='Loading…';try{const requestedPath=path,r=await filesFetch('/api/files?path='+encodeURIComponent(path));if(!r.ok)throw Error(await r.text());const result=parseFiles(await r.arrayBuffer());if(requestedPath==='~')state.homePath=result.path;else if(!state.homePath&&/^\/(?:home|Users)\/[^/]+$/.test(result.path))state.homePath=result.path;Object.assign(state,result,{selected:null});history.replaceState(null,'','?path='+encodeURIComponent(state.path));render()}catch(e){$('#status').textContent=e.message}}
function render(){cancelPreview();resetTypeahead();resetTouchTap();renderCrumbs();$('#home').classList.toggle('selected',state.path===state.homePath);const rows=$('#rows');rows.tabIndex=0;rows.onscroll=()=>{state.lastTouchTap=null};rows.removeAttribute('aria-activedescendant');rows.replaceChildren(...state.entries.map((entry,index)=>{const el=document.createElement('div');el.id=`file-row-${index}`;el.className='row';el.dataset.path=entry.path;el.setAttribute('role','option');el.setAttribute('aria-selected','false');el.innerHTML=`<span class="name"><span class="icon ${entry.directory?'folder':'file'}">${entry.directory?'':'📄'}</span><span class="name-label"></span></span><span class="modified">${fmtDate(entry.modified)}</span><span class="size">${entry.directory?'—':fmtSize(entry.size)}</span>`;el.querySelector('.name-label').textContent=entry.name;el.onclick=()=>{if(consumeSuppressedTouchClick(entry))return;resetTypeahead();select(entry,el,true)};el.onpointerup=e=>handleRowPointerUp(e,entry);el.ondblclick=()=>activateEntry(entry);el.oncontextmenu=e=>{e.preventDefault();resetTypeahead();select(entry,el,true);showMenu(e.clientX,e.clientY,entry)};return el}));$('#status').textContent=`${state.entries.length} items`;$('#preview').innerHTML='<div class="preview-empty">Select a file to preview it.</div>'}
function resetTouchTap(){state.lastTouchTap=null;state.suppressedTouchClick=null}
function activateEntry(entry){state.lastTouchTap=null;entry.directory?load(entry.path):openDefault(entry)}
function handleRowPointerUp(event,entry){if(event.pointerType!=='touch'||!event.isPrimary)return;const now=performance.now(),previous=state.lastTouchTap,isDoubleTap=previous&&previous.path===entry.path&&now-previous.time<=400&&Math.hypot(event.clientX-previous.x,event.clientY-previous.y)<=24;if(!isDoubleTap){state.lastTouchTap={path:entry.path,time:now,x:event.clientX,y:event.clientY};return}state.lastTouchTap=null;state.suppressedTouchClick={path:entry.path,until:now+500};event.preventDefault();event.stopPropagation();activateEntry(entry)}
function consumeSuppressedTouchClick(entry){const suppressed=state.suppressedTouchClick;state.suppressedTouchClick=null;return!!suppressed&&suppressed.path===entry.path&&performance.now()<=suppressed.until}
function renderCrumbs(){const root=state.path.startsWith('/')?'/':'~';const parts=state.path==='~'?[]:state.path.replace(/^~\/?|^\//,'').split('/').filter(Boolean);let path=root;const nodes=[];[root,...parts].forEach((p,i)=>{if(i)path=path==='/'?'/'+p:path+'/'+p;const b=document.createElement('button');b.className='crumb';b.textContent=p;b.onclick=(()=>{const x=path;return()=>load(x)})();nodes.push(b);if(i<parts.length){const s=document.createElement('span');s.className='separator';s.textContent='›';nodes.push(s)}});$('#crumbs').replaceChildren(...nodes)}
function cancelPreview(){if(state.previewController)state.previewController.abort();state.previewController=null;if(state.previewURL)URL.revokeObjectURL(state.previewURL);state.previewURL=null}
function select(entry,el,focus=false){cancelPreview();document.querySelectorAll('.row.selected').forEach(x=>{x.classList.remove('selected');x.setAttribute('aria-selected','false')});el.classList.add('selected');el.setAttribute('aria-selected','true');$('#rows').setAttribute('aria-activedescendant',el.id);state.selected=entry;if(focus)$('#rows').focus({preventScroll:true});if(!entry.directory)preview(entry);else{const pane=$('#preview');pane.innerHTML=`<div class="directory-preview"><div><h2>${escapeHTML(entry.name)}</h2><div class="path">${escapeHTML(entry.path)}</div></div><button class="open-folder" type="button">Open folder</button></div>`;pane.querySelector('.open-folder').onclick=()=>load(entry.path)}}
function selectedIndex(){return state.selected?state.entries.findIndex(entry=>entry.path===state.selected.path):-1}
function selectIndex(index){if(!state.entries.length)return;index=Math.max(0,Math.min(index,state.entries.length-1));const row=$('#rows').children[index];select(state.entries[index],row);row.scrollIntoView({block:'nearest'})}
function resetTypeahead(){state.typeaheadPrefix='';state.typeaheadLastUpdated=0}
function selectEntryMatchingPrefix(prefix,startingAfterSelection){if(!prefix)return false;const selected=selectedIndex(),start=startingAfterSelection?(selected<0?0:selected+1):0;for(let offset=0;offset<state.entries.length;offset++){const index=(start+offset)%state.entries.length;if(state.entries[index].name.toLocaleLowerCase().startsWith(prefix)){selectIndex(index);return true}}return false}
function handleTypeahead(text){if(!state.entries.length)return;const now=Date.now();if(state.typeaheadLastUpdated&&now-state.typeaheadLastUpdated>1000)state.typeaheadPrefix='';state.typeaheadLastUpdated=now;state.typeaheadPrefix+=text.toLocaleLowerCase();if(selectEntryMatchingPrefix(state.typeaheadPrefix,false))return;state.typeaheadPrefix=text.toLocaleLowerCase();selectEntryMatchingPrefix(state.typeaheadPrefix,true)}
function typeaheadText(key){return key&&![...key].some(character=>/[\u0000-\u001f\u007f-\u009f\r\n]/u.test(character))&&[...key].length===1?key:null}
function handleKeyDown(e){if(e.defaultPrevented||e.metaKey||e.ctrlKey||e.altKey||e.target.closest('input,textarea,[contenteditable="true"]'))return;const index=selectedIndex();if(e.key==='ArrowUp'){e.preventDefault();resetTypeahead();selectIndex(index<0?state.entries.length-1:index-1)}else if(e.key==='ArrowDown'){e.preventDefault();resetTypeahead();selectIndex(index<0?0:index+1)}else if(e.key==='Enter'&&index>=0&&state.entries[index].directory){e.preventDefault();load(state.entries[index].path)}else if(e.key==='Backspace'&&state.parent){e.preventDefault();load(state.parent)}else{const text=typeaheadText(e.key);if(text){e.preventDefault();handleTypeahead(text)}}}
async function preview(entry){const pane=$('#preview'),controller=new AbortController();state.previewController=controller;pane.innerHTML='<div class="preview-empty">Loading preview…</div>';try{const options={signal:controller.signal},[pr,or]=await Promise.all([filesFetch('/api/preview?path='+encodeURIComponent(entry.path),options),filesFetch('/api/openers?path='+encodeURIComponent(entry.path),options)]);const openers=or.ok?parseOpeners(await or.arrayBuffer()):[];if(!pr.ok)throw Error(await pr.text());const type=(pr.headers.get('content-type')||'').split(';')[0],blob=await pr.blob();if(controller.signal.aborted||state.selected?.path!==entry.path)return;state.openers=openers;const url=URL.createObjectURL(blob);state.previewURL=url;pane.innerHTML='';const title=document.createElement('h2');title.textContent=entry.name;const path=document.createElement('div');path.className='path';path.textContent=entry.path;const actions=document.createElement('div');actions.className='preview-actions';if(state.openers.length){const open=document.createElement('button');open.textContent='Open';open.onclick=e=>showOpeners(e.currentTarget,entry);actions.append(open)}const dl=document.createElement('a');dl.textContent='Download';dl.href='/api/download?path='+encodeURIComponent(entry.path);actions.append(dl);pane.append(title,path,actions);let content;if(type.startsWith('image/')){content=document.createElement('img');content.src=url}else if(type.startsWith('video/')){content=document.createElement('video');content.controls=true;content.src=url}else if(type.startsWith('audio/')){content=document.createElement('audio');content.controls=true;content.src=url}else if(type==='application/pdf'){content=document.createElement('iframe');content.src=url}else{content=document.createElement('pre');content.textContent=await blob.text()}content.classList.add('preview-content');pane.append(content)}catch(e){if(e.name==='AbortError'||state.selected?.path!==entry.path)return;pane.innerHTML=`<h2>${escapeHTML(entry.name)}</h2><div class="path">${escapeHTML(entry.path)}</div><p class="preview-content">${escapeHTML(e.message)}</p>`}finally{if(state.previewController===controller)state.previewController=null}}
function targetURL(opener){if(!opener.socket)return opener.url;let suffix=opener.url.startsWith(opener.socket)?opener.url.slice(opener.socket.length):'/';if(!suffix.startsWith('/'))suffix='/'+suffix;return 'http+unix://'+encodeURIComponent(opener.socket)+suffix}
async function openDefault(entry){try{const r=await filesFetch('/api/openers?path='+encodeURIComponent(entry.path));const os=parseOpeners(await r.arrayBuffer());if(os[0])location.href=targetURL(os[0]);else throw Error('No app can open this file')}catch(e){$('#status').textContent=e.message}}
function showOpeners(anchor,entry){const r=anchor.getBoundingClientRect();showMenu(r.left,r.bottom+5,entry,true)}function showMenu(x,y,entry,onlyOpen=false){const menu=$('#menu'),buttons=[];if(entry.directory&&!onlyOpen)buttons.push(item('Open',()=>load(entry.path)));for(const o of state.openers)buttons.push(item(`${o.name||o.serviceID}${o.owner?' — '+o.owner:''}`,()=>location.href=targetURL(o)));if(!entry.directory)buttons.push(item('Download',()=>location.href='/api/download?path='+encodeURIComponent(entry.path)));menu.replaceChildren(...buttons);menu.hidden=false;menu.style.left=Math.min(x,innerWidth-230)+'px';menu.style.top=Math.min(y,innerHeight-menu.offsetHeight-8)+'px'}function item(label,fn){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{hideMenu();fn()};return b}function hideMenu(){$('#menu').hidden=true}function escapeHTML(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
$('#home').onclick=()=>load('~');document.addEventListener('keydown',handleKeyDown);document.addEventListener('pointerdown',e=>{if(!e.target.closest('.menu'))hideMenu()});window.addEventListener('popstate',()=>load(new URLSearchParams(location.search).get('path')||'~'));load();})();
